version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejsservice1
    restart: unless-stopped
    ports:
      - "8000:8000"
    